Bump bindgen version
fastly/userfaultfd-rs pull request #10
Opened 2021-01-31 21:37 UTC by jgowans

Attempting to consume this package from one which uses a later version of bindgen, and it seems like the differing version of clang-sys dependencies don't play nicely together. Not entirely sure why possibly/probably due to linking against the system libclang library?... Assuming we need to bump the version of bindgen.

This is the error:

```
cargo build \
    --release \
    --target="aarch64-unknown-linux-musl" \
    --manifest-path="memory-manager/Cargo.toml" \
    --target-dir="/workplace/jgowans/build-aarch64/memory-manager"
    Updating crates.io index
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.56.0`
    ... which is depended on by `memory-manager v0.1.0 (/workplace/jgowans/memory-manager/memory-manager)`
versions that meet the requirements `>=1.0.0, <2.0.0` are: 1.0.3, 1.0.2, 1.0.1, 1.0.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v0.28.0`
    ... which is depended on by `bindgen v0.51.0`
    ... which is depended on by `userfaultfd-sys v0.2.1`
    ... which is depended on by `userfaultfd v0.2.1`
    ... which is depended on by `memory-manager v0.1.0 (/workplace/jgowans/memory-manager/memory-manager)`

failed to select a version for `clang-sys` which could resolve this conflict
Makefile.dev:32: recipe for target 'build' failed
make: *** [build] Error 101
```

2021-02-02 23:36 UTC, pchickey requested changes
Thanks for this PR.
* The latest bindgen is `0.57`, is there any reason we shouldnt be using that instead of `0.56`?
* We have the `default-features = false` set on the bindgen dep to make the dependency tree smaller - I don't believe we need those features, can you leave that turned off?

2021-02-03 07:59 UTC, jgowans commented
Thanks Pat!

Done both changes. I've added the `runtime` feature flag to bindgen as recommended in the change log: https://github.com/rust-lang/rust-bindgen/blob/master/CHANGELOG.md#0520

Without it it doesn't seem to find libclang properly...

```
error: failed to run custom build command for `clang-sys v1.0.3`

Caused by:
  process didn't exit successfully: `/workplace/jgowans/userfaultfd-rs/target/debug/build/clang-sys-5b940c21bebf34cf/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/ANT.AMAZON.COM/jgowans/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.3/build/dynamic.rs:211:45
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Not entirely sure why...

2021-02-03 18:14 UTC, acfoltzer commented
Yeah, the runtime flag looks like the right choice. It just wasn't a thing as of 0.51

2021-02-03 18:14 UTC, pchickey commented
I had not seen that changelog, thanks. I agree the runtime feature seems like the one we want turned on.

2021-02-03 18:15 UTC, pchickey approved these changes

2021-02-03 18:16 UTC, merged

2021-02-03 18:37 UTC, acfoltzer commented
@jgowans released as `0.3.0` due to the major semver bump on the `bindgen` dependency. Thank you!